//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesOfStudent
    {
        public int COSId { get; set; }
        public string CourseName { get; set; }
        public string StudentName { get; set; }
        public int CourseId { get; set; }
        public int TeacherId { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
