//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineStudent
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string MobileNo { get; set; }
        public string StdInstitute { get; set; }
        public int UserId { get; set; }
        public string Address { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
    }
}
