//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int RegId { get; set; }
        public int SubjectId { get; set; }
        public string StudentName { get; set; }
        public double Fee { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
